version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    reviewers:
      - "tpximpact"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      microsoft-packages:
        patterns:
          - "Microsoft.*"
      health-checks:
        patterns:
          - "AspNetCore.HealthChecks.*"
      testing-packages:
        patterns:
          - "NUnit*"
          - "Moq"
          - "coverlet.*"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
